# Generated by Django 3.1 on 2020-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.IntegerField()),
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('idtipodocumento', models.IntegerField()),
                ('documento', models.CharField(max_length=200)),
                ('lugarresidencia', models.CharField(max_length=200)),
                ('fechanacimiento', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipodocumento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
